// Typelizer digest a3a2121bc5112b6df1f8880b46e88e77
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type EventCategory = 'education' | 'community' | 'event';
export type TagCategory = 'generic' | 'format' | 'topic' | 'event_type' | 'education_type';
