// Typelizer digest 2d964c5c27992d7785da07d5cc22c636
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type EventCategory = 'education' | 'community' | 'event';
export type TagCategory = 'format' | 'event_type' | 'education_type' | 'topic' | 'generic';
