// Typelizer digest 5e10d4d5f0c864729e6fa1407fa96627
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {EventCategory} from '@free/types/resources'

type Event = {
  id: number;
  category: EventCategory;
  description: string;
  displayTime: boolean;
  endAt?: unknown;
  imageUrl?: string;
  language: string;
  startAt: unknown;
  tags: unknown;
  timezone: string;
  title: string;
  url?: string;
}

export type { Event };
