// Typelizer digest 7ecb13b24c0228735018a3da0a48f7c4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Tag, EventCategory} from '@free/types/resources'

type Event = {
  id: number;
  category: EventCategory;
  description: string;
  displayTime: boolean;
  endAt?: unknown;
  imageUrl?: string;
  language: string;
  startAt: unknown;
  tags: Array<Tag>;
  timezone: string;
  title: string;
  url?: string;
}

export type { Event };
