// Typelizer digest 9e776ea2f2758cffb1dae98f372cbbd4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Tag, EventCategory} from '@free/types/resources'

type Event = {
  id: number;
  category: EventCategory;
  description: string;
  displayTime: boolean;
  endAt?: string;
  imageUrl?: string;
  language: string;
  startAt: string;
  tags: Array<Tag>;
  timezone: string;
  title: string;
  url?: string;
}

export type { Event };
