// Typelizer digest dbdc23702aead0139ee8f2737a1b76e5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {TagCategory} from '@free/types/resources'

type Tag = {
  category: TagCategory;
  name: string;
}

export type { Tag };
