// Typelizer digest 3ce4c3f7b43644bf4ba5da1c80ace2a6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {TagCategory} from '@free/types/resources'

type Tag = {
  category: TagCategory;
  name: string;
}

export type { Tag };
